# Generated by Django 5.2.7 on 2025-10-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image_url',
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELECONSULTA', 'Teleconsulta')], default='PRESENCIAL', max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
