# Generated by Django 5.2.7 on 2025-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_doctor_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('CARDIOLOGIA', 'Cardiología'), ('NEUROLOGIA', 'Neurología'), ('OFTALMOLOGIA', 'Oftalmología'), ('TRAUMATOLOGIA', 'Traumatología'), ('MEDICINA_GENERAL', 'Medicina General'), ('PEDIATRIA', 'Pediatría')], max_length=20),
        ),
    ]
